//lista com as musicas
const musicas = [
  {
    rank: 1,
    nome: "Like a Rolling Stone",
    artist: "Bob Dylan",
    album: "Highway 61 Revisited",
    year: "1965",
  },
  {
    rank: 2,
    nome: "(I Can't Get No) Satisfaction",
    artist: "The Rolling Stones",
    album: "Out of Our Heads",
    year: "1965",
  },
  {
    rank: 3,
    nome: "Imagine",
    artist: "John Lennon",
    album: "Imagine",
    year: "1971",
  },
  {
    rank: 4,
    nome: "What's Going On",
    artist: "Marvin Gaye",
    album: "What's Going On",
    year: "1971",
  },
  {
    rank: 5,
    nome: "Respect",
    artist: "Aretha Franklin",
    album: "I Never Loved a Man the Way I Love You",
    year: "1967",
  },
  {
    rank: 6,
    nome: "Good Vibrations",
    artist: "The Beach Boys",
    album: "Smiley Smile/Wild Honey",
    year: "1966",
  },
  {
    rank: 7,
    nome: "Johnny B. Goode",
    artist: "Chuck Berry",
    album: "The Anthology",
    year: "1958",
  },
  {
    rank: 8,
    nome: "Hey Jude",
    artist: "The Beatles",
    album: "Hey Jude",
    year: "1968",
  },
  {
    rank: 9,
    nome: "Smells Like Teen Spirit",
    artist: "Nirvana",
    album: "Nevermind",
    year: "1991",
  },
  {
    rank: 10,
    nome: "What'd I Say",
    artist: "Ray Charles",
    album: "What'd I Say",
    year: "1959",
  },
  {
    rank: 11,
    nome: "My Generation",
    artist: "The Who",
    album: "My Generation",
    year: "1965",
  },
  {
    rank: 12,
    nome: "A Change Is Gonna Come",
    artist: "Sam Cooke",
    album: "Portrait of a Legend 1951-1964",
    year: "1964",
  },
  {
    rank: 13,
    nome: "Yesterday",
    artist: "The Beatles",
    album: "Help!",
    year: "1965",
  },
  {
    rank: 14,
    nome: "Blowin' in the Wind",
    artist: "Bob Dylan",
    album: "The Freewheelin' Bob Dylan",
    year: "1963",
  },
  {
    rank: 15,
    nome: "London Calling",
    artist: "The Clash",
    album: "London Calling",
    year: "1980",
  },
  {
    rank: 16,
    nome: "I Want to Hold Your Hand",
    artist: "The Beatles",
    album: "Meet the Beatles!",
    year: "1963",
  },
  {
    rank: 17,
    nome: "Purple Haze",
    artist: "The Jimi Hendrix Experience",
    album: "Are You Experienced?",
    year: "1967",
  },
  {
    rank: 18,
    nome: "Maybellene",
    artist: "Chuck Berry",
    album: "The Anthology",
    year: "1955",
  },
  {
    rank: 19,
    nome: "Hound Dog",
    artist: "Elvis Presley",
    album: " Elvis 30 #1 Hits",
    year: "1956",
  },
  {
    rank: 20,
    nome: "Let It Be",
    artist: "The Beatles",
    album: "Let It Be",
    year: "1970",
  },
  {
    rank: 21,
    nome: "Born to Run",
    artist: "Bruce Springsteen",
    album: "Born to Run",
    year: "1975",
  },
  {
    rank: 22,
    nome: "Be My Baby",
    artist: "The Ronettes",
    album: "The Best of the Ronettes",
    year: "1963",
  },
  {
    rank: 23,
    nome: "In My Life",
    artist: "The Beatles",
    album: "Rubber Soul",
    year: "1965",
  },
  {
    rank: 24,
    nome: "People Get Ready",
    artist: "The Impressions",
    album: "The Very Best of the Impressions",
    year: "1965",
  },
  {
    rank: 25,
    nome: "God Only Knows",
    artist: "The Beach Boys",
    album: "Pet Sounds",
    year: "1966",
  },
  {
    rank: 26,
    nome: "(Sittin' On) The Dock of the Bay",
    artist: "Otis Redding",
    album: "The Dock of the Bay",
    year: "1968",
  },
  {
    rank: 27,
    nome: "Layla",
    artist: "Derek and the Dominos",
    album: "Layla And Other Assorted Love Songs",
    year: "1970",
  },
  {
    rank: 28,
    nome: "A Day in the Life",
    artist: "The Beatles",
    album: "Sgt. Pepper's Lonely Hearts Club Band",
    year: "1967",
  },
  {
    rank: 29,
    nome: "Help!",
    artist: "The Beatles",
    album: "Help!",
    year: "1965",
  },
  {
    rank: 30,
    nome: "I Walk the Line",
    artist: "Johnny Cash",
    album: "The Complete Original Sun Singles",
    year: "1956",
  },
  {
    rank: 31,
    nome: "Stairway to Heaven",
    artist: "Led Zeppelin",
    album: "Led Zeppelin IV",
    year: "1971",
  },
  {
    rank: 32,
    nome: "Sympathy for the Devil",
    artist: "The Rolling Stones",
    album: "Beggars Banquet",
    year: "1968",
  },
  {
    rank: 33,
    nome: "River Deep - Mountain High",
    artist: "Ike & Tina Turner",
    album: "Proud Mary: The Best of Ike and Tina Turner",
    year: "1966",
  },
  {
    rank: 34,
    nome: "You've Lost That Lovin' Feelin'",
    artist: "The Righteous Brothers",
    album: "Anthology 1962-1974",
    year: "1964",
  },
  {
    rank: 35,
    nome: "Light My Fire",
    artist: "The Doors",
    album: "The Doors",
    year: "1967",
  },
  {
    rank: 36,
    nome: "One",
    artist: "U2",
    album: "Achtung Baby",
    year: "1991",
  },
  {
    rank: 37,
    nome: "No Woman, No Cry",
    artist: "Bob Marley & The Wailers",
    album: "Natty Dread",
    year: "1975",
  },
  {
    rank: 38,
    nome: "Gimme Shelter",
    artist: "The Rolling Stones",
    album: "Let It Bleed",
    year: "1969",
  },
  {
    rank: 39,
    nome: "That'll Be the Day",
    artist: "Buddy Holly & The Crickets",
    album: "Greatest Hits",
    year: "1957",
  },
  {
    rank: 40,
    nome: "Dancing in the Street",
    artist: "Martha and the Vandellas",
    album: "The Ultimate Collection",
    year: "1964",
  },
  {
    rank: 41,
    nome: "The Weight",
    artist: "The Band",
    album: "Music From Big Pink",
    year: "1968",
  },
  {
    rank: 42,
    nome: "Waterloo Sunset",
    artist: "The Kinks",
    album: "Something Else By The Kinks",
    year: "1968",
  },
  {
    rank: 43,
    nome: "Tutti-Frutti",
    artist: "Little Richard",
    album: "The Georgia Peach",
    year: "1956",
  },
  {
    rank: 44,
    nome: "Georgia On My Mind",
    artist: "Ray Charles",
    album: "Ultimate Hits Collection",
    year: "1960",
  },
  {
    rank: 45,
    nome: "Heartbreak Hotel",
    artist: "Elvis Presley",
    album: "Elvis 30 #1 Hits",
    year: "1956",
  },
  {
    rank: 46,
    nome: "Heroes",
    artist: "David Bowie",
    album: "Heroes",
    year: "1977",
  },
  {
    rank: 47,
    nome: "All Along the Watchtower",
    artist: "The Jimi Hendrix Experience",
    album: "Electric Ladyland",
    year: "1968",
  },
  {
    rank: 48,
    nome: "Bridge Over Troubled Water",
    artist: "Simon & Garfunkel",
    album: "Bridge Over Troubled Water",
    year: "1970",
  },
  {
    rank: 49,
    nome: "Hotel California",
    artist: "Eagles",
    album: "Hotel California",
    year: "1976",
  },
  {
    rank: 50,
    nome: "The Tracks Of My Tears",
    artist: "Smokey Robinson and the Miracles",
    album: "Going to a Go-Go",
    year: "1965",
  },
  {
    rank: 51,
    nome: "The Message",
    artist: "Grandmaster Flash and the Furious Five",
    album: "The Best of Sugar Hill Records",
    year: "1980",
  },
  {
    rank: 52,
    nome: "When Doves Cry",
    artist: "Prince and The Revolution",
    album: "Purple Rain",
    year: "1984",
  },
  {
    rank: 53,
    nome: "When A Man Loves A Woman",
    artist: "Percy Sledge",
    album: "It Tears Me Up: The Best of Percy Sledge",
    year: "1966",
  },
  {
    rank: 54,
    nome: "Louie Louie",
    artist: "The Kingsmen",
    album: "The Best of the Kingsmen",
    year: "1963",
  },
  {
    rank: 55,
    nome: "Long Tall Sally",
    artist: "Little Richard",
    album: "The Georgia Peach",
    year: "1956",
  },
  {
    rank: 56,
    nome: "Anarchy in the U.K.",
    artist: "Sex Pistols",
    album: "Never Mind the Bollocks, Here's the Sex Pistols",
    year: "1976",
  },
  {
    rank: 57,
    nome: "A Whiter Shade of Pale",
    artist: "Procol Harum",
    album: "Greatest Hits",
    year: "1967",
  },
  {
    rank: 58,
    nome: "Billie Jean",
    artist: "Michael Jackson",
    album: "Thriller",
    year: "1983",
  },
  {
    rank: 59,
    nome: "The Times They Are a-Changin'",
    artist: "Bob Dylan",
    album: "The Times They Are A-Changin'",
    year: "1964",
  },
  {
    rank: 60,
    nome: "Let's Stay Together",
    artist: "Al Green",
    album: "Let's Stay Together",
    year: "1971",
  },
  {
    rank: 61,
    nome: "Whole Lotta Shakin' Going On",
    artist: "Jerry Lee Lewis",
    album: "Original Sun Greatest Hits",
    year: "1957",
  },
  {
    rank: 62,
    nome: "Bo Diddley",
    artist: "Bo Diddley",
    album: "His Best: The Chess 50th Anniversary Collection",
    year: "1955",
  },
  {
    rank: 63,
    nome: "For What It's Worth",
    artist: "Buffalo Springfield",
    album: "Buffalo Springfield",
    year: "1967",
  },
  {
    rank: 64,
    nome: "She Loves You",
    artist: "The Beatles",
    album: "The Beatles 1",
    year: "1963",
  },
  {
    rank: 65,
    nome: "Sunshine of Your Love",
    artist: "Cream",
    album: "Disraeli Gears",
    year: "1968",
  },
  {
    rank: 66,
    nome: "Redemption Song",
    artist: "Bob Marley & The Wailers",
    album: "Uprising",
    year: "1980",
  },
  {
    rank: 67,
    nome: "Jailhouse Rock",
    artist: "Elvis Presley",
    album: "Elvis 30 #1 Hits",
    year: "1957",
  },
  {
    rank: 68,
    nome: "Tangled Up in Blue",
    artist: "Bob Dylan",
    album: "Blood on the Tracks",
    year: "1975",
  },
  {
    rank: 69,
    nome: "Crying",
    artist: "Roy Orbison",
    album: "For the Lonely: 18 Greatest Hits",
    year: "1961",
  },
  {
    rank: 70,
    nome: "Walk On By",
    artist: "Dionne Warwick",
    album: "The Dionne Warwick Collection: Her All-Time Greatest Hits",
    year: "1964",
  },
  {
    rank: 71,
    nome: "Papa's Got a Brand New Bag",
    artist: "James Brown",
    album: "50th Anniversary Collection",
    year: "1966",
  },
  {
    rank: 72,
    nome: "California Girls",
    artist: "The Beach Boys",
    album: "Sounds of Summer: The Very Best of the Beach Boys",
    year: "1965",
  },
  {
    rank: 73,
    nome: "Superstition",
    artist: "Stevie Wonder",
    album: "Talking Book",
    year: "1973",
  },
  {
    rank: 74,
    nome: "Summertime Blues",
    artist: "Eddie Cochran",
    album: "Somethin' Else",
    year: "1958",
  },
  {
    rank: 75,
    nome: "Whole Lotta Love",
    artist: "Led Zeppelin",
    album: "Led Zeppelin II",
    year: "1969",
  },
  {
    rank: 76,
    nome: "Strawberry Fields Forever",
    artist: "The Beatles",
    album: "Magical Mystery Tour",
    year: "1967",
  },
  {
    rank: 77,
    nome: "Mystery Train",
    artist: "Elvis Presley",
    album: "Sunrise",
    year: "1955",
  },
  {
    rank: 78,
    nome: "I Got You (I Feel Good)",
    artist: "James Brown",
    album: "James Brown 50th Anniversary Collection",
    year: "1966",
  },
  {
    rank: 79,
    nome: "Mr. Tambourine Man",
    artist: "The Byrds",
    album: "Mr. Tambourine Man",
    year: "1965",
  },
  {
    rank: 80,
    nome: "You Really Got Me",
    artist: "The Kinks",
    album: "Kinks",
    year: "1964",
  },
  {
    rank: 81,
    nome: "I Heard It Through the Grapevine",
    artist: "Marvin Gaye",
    album: "Every Motown Hit",
    year: "1968",
  },
  {
    rank: 82,
    nome: "Blueberry Hill",
    artist: "Fats Domino",
    album: "The Fats Domino Jukebox",
    year: "1956",
  },
  {
    rank: 83,
    nome: "Norwegian Wood (This Bird Has Flown)",
    artist: "The Beatles",
    album: "Rubber Soul",
    year: "1965",
  },
  {
    rank: 84,
    nome: "Every Breath You Take",
    artist: "The Police",
    album: "Synchronicity",
    year: "1983",
  },
  {
    rank: 85,
    nome: "Crazy",
    artist: "Patsy Cline",
    album: "Patsy Cline's Greatest Hits",
    year: "1961",
  },
  {
    rank: 86,
    nome: "Thunder Road",
    artist: "Bruce Springsteen",
    album: "Born to Run",
    year: "1975",
  },
  {
    rank: 87,
    nome: "Ring of Fire",
    artist: "Johnny Cash",
    album: "The Man in Black: His Greatest Hits",
    year: "1963",
  },
  {
    rank: 88,
    nome: "My Girl",
    artist: "The Temptations",
    album: "The Temptations Sing Smokey",
    year: "1965",
  },
  {
    rank: 89,
    nome: "California Dreamin'",
    artist: "The Mamas & The Papas",
    album: "If You Can Believe Your Eyes And Ears",
    year: "1965",
  },
  {
    rank: 90,
    nome: "In The Still Of The Nite",
    artist: "The Five Satins",
    album: "The Five Satins: Their Greatest Hits",
    year: "1956",
  },
  {
    rank: 91,
    nome: "Suspicious Minds",
    artist: "Elvis Presley",
    album: "Elvis 30 #1 Hits",
    year: "1969",
  },
  {
    rank: 92,
    nome: "Blitzkrieg Bop",
    artist: "Ramones",
    album: "Ramones",
    year: "1976",
  },
  {
    rank: 93,
    nome: "I Still Haven't Found What I'm Looking For",
    artist: "U2",
    album: "The Joshua Tree",
    year: "1987",
  },
  {
    rank: 94,
    nome: "Good Golly",
    artist: "Little Richard",
    album: "The Georgia Peach",
    year: "1958",
  },
  {
    rank: 95,
    nome: "Blue Suede Shoes",
    artist: "Carl Perkins",
    album: "Original Sun Greatest Hits",
    year: "1956",
  },
  {
    rank: 96,
    nome: "Great Balls of Fire",
    artist: "Jerry Lee Lewis",
    album: "Original Sun Greatest Hits",
    year: "1957",
  },
  {
    rank: 97,
    nome: "Roll Over Beethoven",
    artist: "Chuck Berry",
    album: "The Anthology",
    year: "1956",
  },
  {
    rank: 98,
    nome: "Love And Happiness",
    artist: "Al Green",
    album: "I'm Still in Love With You",
    year: "1972",
  },
  {
    rank: 99,
    nome: "Fortunate Son",
    artist: "Creedence Clearwater Revival",
    album: "Willy And The Poor Boys",
    year: "1970",
  },
  {
    rank: 100,
    nome: "Crazy",
    artist: "Gnarls Barkley",
    album: "St. Elsewhere",
    year: "2006",
  },
  {
    rank: 101,
    nome: "You Can't Always Get What You Want",
    artist: "The Rolling Stones",
    album: "Let It Bleed",
    year: "1969",
  },
  {
    rank: 102,
    nome: "Voodoo Child (Slight Return)",
    artist: "The Jimi Hendrix Experience",
    album: "Electric Ladyland",
    year: "1968",
  },
  {
    rank: 103,
    nome: "Be-Bop-A-Lula",
    artist: "Gene Vincent & His Blue Caps",
    album: "The Screaming End: The Best of Gene Vincent and His Blue Caps",
    year: "1956",
  },
  {
    rank: 104,
    nome: "Hot Stuff",
    artist: "Donna Summer",
    album: "Bad Girls",
    year: "1979",
  },
  {
    rank: 105,
    nome: "Living For The City",
    artist: "Stevie Wonder",
    album: "Innervisions",
    year: "1973",
  },
  {
    rank: 106,
    nome: "The Boxer",
    artist: "Simon & Garfunkel",
    album: "Bridge Over Troubled Water",
    year: "1969",
  },
  {
    rank: 107,
    nome: "Mr. Tambourine Man",
    artist: "Bob Dylan",
    album: "Bringing It All Back Home",
    year: "1965",
  },
  {
    rank: 108,
    nome: "Not Fade Away",
    artist: "Buddy Holly & The Crickets",
    album: "Greatest Hits",
    year: "1957",
  },
  {
    rank: 109,
    nome: "Little Red Corvette",
    artist: "Prince",
    album: "1999",
    year: "1983",
  },
  {
    rank: 110,
    nome: "Brown Eyed Girl",
    artist: "Van Morrison",
    album: "Blowin' Your Mind",
    year: "1967",
  },
  {
    rank: 111,
    nome: "I've Been Loving You Too Long (To Stop Now)",
    artist: "Otis Redding",
    album: "Otis Blue: Otis Redding Sings Soul",
    year: "1965",
  },
  {
    rank: 112,
    nome: "I'm So Lonesome I Could Cry",
    artist: "Hank Williams",
    album: "The Ultimate Collection",
    year: "1949",
  },
  {
    rank: 113,
    nome: "That's All Right",
    artist: "Elvis Presley",
    album: "Sunrise",
    year: "1954",
  },
  {
    rank: 114,
    nome: "Up On the Roof",
    artist: "The Drifters",
    album: "The Very Best of the Drifters",
    year: "1962",
  },
  {
    rank: 115,
    nome: "You Send Me",
    artist: "Sam Cooke",
    album: "Greatest Hits",
    year: "1957",
  },
  {
    rank: 116,
    nome: "Honky Tonk Women",
    artist: "The Rolling Stones",
    album: "Let It Bleed",
    year: "1969",
  },
  {
    rank: 117,
    nome: "Take Me To The River",
    artist: "Al Green",
    album: "Al Green Explores Your Mind",
    year: "1974",
  },
  {
    rank: 118,
    nome: "Crazy in Love (feat.  Jay-Z)",
    artist: "Beyoncé",
    album: "Dangerously in Love",
    year: "2003",
  },
  {
    rank: 119,
    nome: "Shout (Parts 1 & 2)",
    artist: "The Isley Brothers",
    album: "The Isley Brothers Story, Vol. 1: Rockin' Soul",
    year: "1959",
  },
  {
    rank: 120,
    nome: "Go Your Own Way",
    artist: "Fleetwood Mac",
    album: "Rumours",
    year: "1977",
  },
  {
    rank: 121,
    nome: "I Want You Back",
    artist: "The Jackson 5",
    album: "The Ultimate Collection",
    year: "1969",
  },
  {
    rank: 122,
    nome: "Stand By Me",
    artist: "Ben E. King",
    album: "The Very Best of Ben E. King",
    year: "1961",
  },
  {
    rank: 123,
    nome: "The House of the Rising Sun",
    artist: "The Animals",
    album: "The Best of the Animals",
    year: "1964",
  },
  {
    rank: 124,
    nome: "It's A Man's Man's Man's World",
    artist: "James Brown",
    album: "50th Anniversary Collection",
    year: "1966",
  },
  {
    rank: 125,
    nome: "Jumpin' Jack Flash",
    artist: "The Rolling Stones",
    album: "Forty Licks",
    year: "1968",
  },
  {
    rank: 126,
    nome: "Will You Love Me Tomorrow",
    artist: "The Shirelles",
    album: "Girl Group Greats",
    year: "1960",
  },
  {
    rank: 127,
    nome: "Shake",
    artist: "Big Joe Turner",
    album: "The Very Best of Big Joe Turner",
    year: "1954",
  },
  {
    rank: 128,
    nome: "Changes",
    artist: "David Bowie",
    album: "Hunky Dory",
    year: "1971",
  },
  {
    rank: 129,
    nome: "Rock and Roll Music",
    artist: "Chuck Berry",
    album: "Johnny B. Goode: His Complete '50s Chess Recordings",
    year: "1957",
  },
  {
    rank: 130,
    nome: "Born to Be Wild",
    artist: "Steppenwolf",
    album: "Steppenwolf",
    year: "1968",
  },
  {
    rank: 131,
    nome: "Maggie May",
    artist: "Rod Stewart",
    album: "Every Picture Tells A Story",
    year: "1971",
  },
  {
    rank: 132,
    nome: "With or Without You",
    artist: "U2",
    album: "The Joshua Tree",
    year: "1987",
  },
  {
    rank: 133,
    nome: "Who Do You Love?",
    artist: "Bo Diddley",
    album: "His Best: The Chess 50th Anniversary Collection",
    year: "1957",
  },
  {
    rank: 134,
    nome: "Won't Get Fooled Again",
    artist: "The Who",
    album: "Who's Next",
    year: "1971",
  },
  {
    rank: 135,
    nome: "In the Midnight Hour",
    artist: "Wilson Pickett",
    album: "The Very Best of Wilson Pickett",
    year: "1965",
  },
  {
    rank: 136,
    nome: "While My Guitar Gently Weeps",
    artist: "The Beatles",
    album: "The Beatles",
    year: "1968",
  },
  {
    rank: 137,
    nome: "Your Song",
    artist: "Elton John",
    album: "Greatest Hits",
    year: "1970",
  },
  {
    rank: 138,
    nome: "Eleanor Rigby",
    artist: "The Beatles",
    album: "Revolver",
    year: "1966",
  },
  {
    rank: 139,
    nome: "Family Affair",
    artist: "Sly & The Family Stone",
    album: "There's a Riot Goin' On",
    year: "1971",
  },
  {
    rank: 140,
    nome: "I Saw Her Standing There",
    artist: "The Beatles",
    album: "Please Please Me",
    year: "1964",
  },
  {
    rank: 141,
    nome: "Kashmir",
    artist: "Led Zeppelin",
    album: "Physical Graffiti",
    year: "1975",
  },
  {
    rank: 142,
    nome: "All I Have to Do Is Dream",
    artist: "The Everly Brothers",
    album: "All-Time Original Hits",
    year: "1958",
  },
  {
    rank: 143,
    nome: "Please, Please, Please",
    artist: "James Brown",
    album: "50th Anniversary Collection",
    year: "1956",
  },
  {
    rank: 144,
    nome: "Purple Rain",
    artist: "Prince and The Revolution",
    album: "Purple Rain",
    year: "1984",
  },
  {
    rank: 145,
    nome: "I Wanna Be Sedated",
    artist: "Ramones",
    album: "Road to Ruin",
    year: "1978",
  },
  {
    rank: 146,
    nome: "Everyday People",
    artist: "Sly & The Family Stone",
    album: "Stand!",
    year: "1968",
  },
  {
    rank: 147,
    nome: "Rock Lobster",
    artist: "The B-52's",
    album: "The B-52's",
    year: "1979",
  },
  {
    rank: 148,
    nome: "Me And Bobby McGee",
    artist: "Janis Joplin",
    album: "Pearl",
    year: "1971",
  },
  {
    rank: 149,
    nome: "Lust For Life",
    artist: "Iggy Pop",
    album: "Lust For Life",
    year: "1977",
  },
  {
    rank: 150,
    nome: "Cathy's Clown",
    artist: "The Everly Brothers",
    album: "All-Time Original Hits",
    year: "1960",
  },
  {
    rank: 151,
    nome: "Eight Miles High",
    artist: "The Byrds",
    album: "Fifth Dimension",
    year: "1966",
  },
  {
    rank: 152,
    nome: "Earth Angel",
    artist: "The Penguins",
    album: "Earth Angel",
    year: "1954",
  },
  {
    rank: 153,
    nome: "Foxey Lady",
    artist: "The Jimi Hendrix Experience",
    album: "Are You Experienced?",
    year: "1965",
  },
  {
    rank: 154,
    nome: "A Hard Day's Night",
    artist: "The Beatles",
    album: "A Hard Day's Night",
    year: "1964",
  },
  {
    rank: 155,
    nome: "Rave On",
    artist: "Buddy Holly & The Crickets",
    album: "Buddy Holly: Greatest Hits",
    year: "1958",
  },
  {
    rank: 156,
    nome: "Proud Mary",
    artist: "Creedence Clearwater Revival",
    album: "Bayou Country",
    year: "1969",
  },
  {
    rank: 157,
    nome: "The Sound of Silence",
    artist: "Simon & Garfunkel",
    album: "Sounds of Silence",
    year: "1965",
  },
  {
    rank: 158,
    nome: "I Only Have Eyes for You",
    artist: "The Flamingos",
    album: "The Best of the Flamingos",
    year: "1959",
  },
  {
    rank: 159,
    nome: "(We're Gonna) Rock Around The Clock",
    artist: "Bill Haley & His Comets",
    album: "The Best of Bill Haley and His Comets",
    year: "1954",
  },
  {
    rank: 160,
    nome: "Moment of Surrender",
    artist: "U2",
    album: "No Line on the Horizon",
    year: "2009",
  },
  {
    rank: 161,
    nome: "I'm Waiting for the Man",
    artist: "The Velvet Underground",
    album: "The Velvet Underground & Nico",
    year: "1967",
  },
  {
    rank: 162,
    nome: "Bring the Noise",
    artist: "Public Enemy",
    album: "It Takes a Nation of Millions to Hold Us Back",
    year: "1988",
  },
  {
    rank: 163,
    nome: "Folsom Prison Blues",
    artist: "Johnny Cash",
    album: "The Essential Johnny Cash",
    year: "1956",
  },
  {
    rank: 164,
    nome: "I Can't Stop Loving You",
    artist: "Ray Charles",
    album: "Modern Sounds in Country and Western Music",
    year: "1962",
  },
  {
    rank: 165,
    nome: "Nothing Compares 2 U",
    artist: "Sinead O'Connor",
    album: "I Do Not Want What I Haven't Got",
    year: "1990",
  },
  {
    rank: 166,
    nome: "Bohemian Rhapsody",
    artist: "Queen",
    album: "A Night at the Opera",
    year: "1975",
  },
  {
    rank: 167,
    nome: "Fast Car",
    artist: "Tracy Chapman",
    album: "Tracy Chapman",
    year: "1988",
  },
  {
    rank: 168,
    nome: "Let's Get It On",
    artist: "Marvin Gaye",
    album: "Let's Get It On",
    year: "1973",
  },
  {
    rank: 169,
    nome: "Papa Was a Rollin' Stone",
    artist: "The Temptations",
    album: "Anthology",
    year: "1972",
  },
  {
    rank: 170,
    nome: "Losing My Religion",
    artist: "R.E.M.",
    album: "Out of Time",
    year: "1991",
  },
  {
    rank: 171,
    nome: "Both Sides Now",
    artist: "Joni Mitchell",
    album: "Clouds",
    year: "1969",
  },
  {
    rank: 172,
    nome: "99 Problems",
    artist: "Jay-Z",
    album: "The Black Album",
    year: "2004",
  },
  {
    rank: 173,
    nome: "Dream On",
    artist: "Aerosmith",
    album: "Aerosmith",
    year: "1973",
  },
  {
    rank: 174,
    nome: "Dancing Queen",
    artist: "ABBA",
    album: "Arrival",
    year: "1976",
  },
  {
    rank: 175,
    nome: "God Save the Queen",
    artist: "Sex Pistols",
    album: "Never Mind the Bollocks, Here's the Sex Pistols",
    year: "1977",
  },
  {
    rank: 176,
    nome: "Paint It, Black",
    artist: "The Rolling Stones",
    album: "Aftermath",
    year: "1966",
  },
  {
    rank: 177,
    nome: "I Fought the Law",
    artist: "The Bobby Fuller Four",
    album: "I Fought the Law: The Best of the Bobby Fuller Four",
    year: "1966",
  },
  {
    rank: 178,
    nome: "Don't Worry Baby",
    artist: "The Beach Boys",
    album: "Sounds of Summer",
    year: "1964",
  },
  {
    rank: 179,
    nome: "Free Fallin'",
    artist: "Tom Petty",
    album: "Full Moon Fever",
    year: "1989",
  },
  {
    rank: 180,
    nome: "September Gurls",
    artist: "Big Star",
    album: "Radio City",
    year: "1974",
  },
  {
    rank: 181,
    nome: "Love Will Tear Us Apart",
    artist: "Joy Division",
    album: "Substance 1977-1980",
    year: "1980",
  },
  {
    rank: 182,
    nome: "Hey Ya!",
    artist: "OutKast",
    album: "Speakerboxxx/The Love Below",
    year: "2003",
  },
  {
    rank: 183,
    nome: "Green Onions",
    artist: "Booker T. & The MG's",
    album: "Green Onions",
    year: "1962",
  },
  {
    rank: 184,
    nome: "Save the Last Dance for Me",
    artist: "The Drifters",
    album: "The Drifters' Golden Hits",
    year: "1960",
  },
  {
    rank: 185,
    nome: "The Thrill Is Gone",
    artist: "B.B. King",
    album: "Greatest Hits",
    year: "1969",
  },
  {
    rank: 186,
    nome: "Please Please Me",
    artist: "The Beatles",
    album: "Please Please Me",
    year: "1964",
  },
  {
    rank: 187,
    nome: "Desolation Row",
    artist: "Bob Dylan",
    album: "Highway 61 Revisited",
    year: "1965",
  },
  {
    rank: 188,
    nome: "Who'll Stop the Rain",
    artist: "Creedence Clearwater Revival",
    album: "Cosmo's Factory",
    year: "1970",
  },
  {
    rank: 189,
    nome: "I Never Loved a Man (the Way I Love You)",
    artist: "Aretha Franklin",
    album: "I Never Loved a Man (the Way I Love You)",
    year: "1967",
  },
  {
    rank: 190,
    nome: "Back in Black",
    artist: "AC/DC",
    album: "Back in Black",
    year: "1980",
  },
  {
    rank: 191,
    nome: "Stayin' Alive",
    artist: "Bee Gees",
    album: "Saturday Night Fever",
    year: "1977",
  },
  {
    rank: 192,
    nome: "Knocking On Heaven's Door",
    artist: "Bob Dylan",
    album: "The Essential Bob Dylan",
    year: "1973",
  },
  {
    rank: 193,
    nome: "Free Bird",
    artist: "Lynyrd Skynyrd",
    album: "One More From the Road",
    year: "1973",
  },
  {
    rank: 194,
    nome: "Rehab",
    artist: "Amy Winehouse",
    album: "Back to Black",
    year: "2007",
  },
  {
    rank: 195,
    nome: "Wichita Lineman",
    artist: "Glen Campbell",
    album: "Wichita Lineman",
    year: "1968",
  },
  {
    rank: 196,
    nome: "There Goes My Baby",
    artist: "The Drifters",
    album: "The Very Best of the Drifters",
    year: "1959",
  },
  {
    rank: 197,
    nome: "Peggy Sue",
    artist: "Buddy Holly",
    album: "Greatest Hits",
    year: "1957",
  },
  {
    rank: 198,
    nome: "Sweet Child o' Mine",
    artist: "Guns N' Roses",
    album: "Appetite for Destruction",
    year: "1987",
  },
  {
    rank: 199,
    nome: "Maybe",
    artist: "The Chantels",
    album: "The Best of the Chantels",
    year: "1957",
  },
  {
    rank: 200,
    nome: "Don't Be Cruel",
    artist: "Elvis Presley",
    album: "Elvis: 30 #1 Hits",
    year: "1956",
  },
  {
    rank: 201,
    nome: "Hey Joe",
    artist: "The Jimi Hendrix Experience",
    album: "Are You Experienced?",
    year: "1966",
  },
  {
    rank: 202,
    nome: "Flash Light",
    artist: "Parliament",
    album: "Funkentelechy vs. the Placebo Syndrome",
    year: "1977",
  },
  {
    rank: 203,
    nome: "Loser",
    artist: "Beck",
    album: "Mellow Gold",
    year: "1993",
  },
  {
    rank: 204,
    nome: "Bizarre Love Triangle",
    artist: "New Order",
    album: "Substance",
    year: "1986",
  },
  {
    rank: 205,
    nome: "Come Together",
    artist: "The Beatles",
    album: "Abbey Road",
    year: "1969",
  },
  {
    rank: 206,
    nome: "Positively 4th Street",
    artist: "Bob Dylan",
    album: "The Essential Bob Dylan",
    year: "1965",
  },
  {
    rank: 207,
    nome: "Try a Little Tenderness",
    artist: "Otis Redding",
    album: "Very Best of Otis Redding",
    year: "1966",
  },
  {
    rank: 208,
    nome: "Lean on Me",
    artist: "Bill Withers",
    album: "Lean on Me",
    year: "1972",
  },
  {
    rank: 209,
    nome: "Reach Out I'll Be There",
    artist: "The Four Tops",
    album: "The Ultimate Collection",
    year: "1966",
  },
  {
    rank: 210,
    nome: "Bye Bye Love",
    artist: "The Everly Brothers",
    album: "All-Time Original Hits",
    year: "1957",
  },
  {
    rank: 211,
    nome: "Gloria",
    artist: "Them",
    album: "The Story of Them",
    year: "1965",
  },
  {
    rank: 212,
    nome: "In My Room",
    artist: "The Beach Boys",
    album: "Surfer Girl/Shut Down, Volume 2",
    year: "1963",
  },
  {
    rank: 213,
    nome: "96 Tears",
    artist: "? and the Mysterians",
    album: "More Action",
    year: "1966",
  },
  {
    rank: 214,
    nome: "Caroline, No",
    artist: "The Beach Boys",
    album: "Pet Sounds",
    year: "1966",
  },
  {
    rank: 215,
    nome: "1999",
    artist: "Prince",
    album: "1999",
    year: "1982",
  },
  {
    rank: 216,
    nome: "Rockin' in the Free World",
    artist: "Neil Young",
    album: "Freedom",
    year: "1989",
  },
  {
    rank: 217,
    nome: "Your Cheatin' Heart",
    artist: "Hank Williams",
    album: "The Ultimate Collection",
    year: "1953",
  },
  {
    rank: 218,
    nome: "Do You Believe In Magic",
    artist: "The Lovin' Spoonful",
    album: "Do You Believe in Magic",
    year: "1965",
  },
  {
    rank: 219,
    nome: "Jolene",
    artist: "Dolly Parton",
    album: "Jolene",
    year: "1974",
  },
  {
    rank: 220,
    nome: "Boom Boom",
    artist: "John Lee Hooker",
    album: "The Very Best of John Lee Hooker",
    year: "1963",
  },
  {
    rank: 221,
    nome: "Spoonful",
    artist: "Howlin' Wolf",
    album: "Anniversary Collection",
    year: "1960",
  },
  {
    rank: 222,
    nome: "Walk away Renée",
    artist: "The Left Banke",
    album: "There's Gonna Be a Storm",
    year: "1966",
  },
  {
    rank: 223,
    nome: "Walk on the Wild Side",
    artist: "Lou Reed",
    album: "Transformer",
    year: "1972",
  },
  {
    rank: 224,
    nome: "Oh",
    artist: "Roy Orbison",
    album: "For the Lonely: 18 Greatest Hits",
    year: "1964",
  },
  {
    rank: 225,
    nome: "Dance To The Music",
    artist: "Sly & The Family Stone",
    album: "Dance to the Music",
    year: "1968",
  },
  {
    rank: 226,
    nome: "Hoochie Coochie Man",
    artist: "Muddy Waters",
    album: "The Anthology",
    year: "1954",
  },
  {
    rank: 227,
    nome: "Fire and Rain",
    artist: "James Taylor",
    album: "Sweet Baby James",
    year: "1970",
  },
  {
    rank: 228,
    nome: "Should I Stay or Should I Go",
    artist: "The Clash",
    album: "Combat Rock",
    year: "1982",
  },
  {
    rank: 229,
    nome: "Good Times",
    artist: "Chic",
    album: "Risqué",
    year: "1979",
  },
  {
    rank: 230,
    nome: "Mannish Boy",
    artist: "Muddy Waters",
    album: "The Anthology",
    year: "1955",
  },
  {
    rank: 231,
    nome: "Moondance",
    artist: "Van Morrison",
    album: "Moondance",
    year: "1970",
  },
  {
    rank: 232,
    nome: "Just Like a Woman",
    artist: "Bob Dylan",
    album: "Blonde on Blonde",
    year: "1966",
  },
  {
    rank: 233,
    nome: "Sexual Healing",
    artist: "Marvin Gaye",
    album: "Midnight Love",
    year: "1982",
  },
  {
    rank: 234,
    nome: "Only the Lonely",
    artist: "Roy Orbison",
    album: "For the Lonely: 18 Greatest Hits",
    year: "1960",
  },
  {
    rank: 235,
    nome: "We Gotta Get Out Of This Place",
    artist: "The Animals",
    album: "Retrospective",
    year: "1965",
  },
  {
    rank: 236,
    nome: "Paper Planes",
    artist: "M.I.A.",
    album: "Kala",
    year: "2008",
  },
  {
    rank: 237,
    nome: "I'll Feel A Whole Lot Better",
    artist: "The Byrds",
    album: "Mr. Tambourine Man",
    year: "1965",
  },
  {
    rank: 238,
    nome: "Everyday",
    artist: "Buddy Holly & The Crickets",
    album: "Best of Buddy Holly",
    year: "1957",
  },
  {
    rank: 239,
    nome: "I Got a Woman",
    artist: "Ray Charles",
    album: "Atlantic Singles",
    year: "1954",
  },
  {
    rank: 240,
    nome: "Planet Rock",
    artist: "Afrika Bambaataa & the Soulsonic Force",
    album: "Looking for the Perfect Beat 1980-1985",
    year: "1982",
  },
  {
    rank: 241,
    nome: "I Fall to Pieces",
    artist: "Patsy Cline",
    album: "12 Greatest Hits",
    year: "1961",
  },
  {
    rank: 242,
    nome: "Son of a Preacher Man",
    artist: "Dusty Springfield",
    album: "Dusty in Memphis",
    year: "1968",
  },
  {
    rank: 243,
    nome: "The Wanderer",
    artist: "Dion",
    album: "Runaround Sue",
    year: "1961",
  },
  {
    rank: 244,
    nome: "Stand!",
    artist: "Sly & The Family Stone",
    album: "Stand!",
    year: "1969",
  },
  {
    rank: 245,
    nome: "Rocket Man (I Think It's Going To Be A Long, Long Time)",
    artist: "Elton John",
    album: "Honky Chateau",
    year: "1972",
  },
  {
    rank: 246,
    nome: "Love Shack",
    artist: "The B-52's",
    album: "Cosmic Thing",
    year: "1989",
  },
  {
    rank: 247,
    nome: "Gimme Some Lovin'",
    artist: "The Spencer Davis Group",
    album: "Gimme Some Lovin'",
    year: "1966",
  },
  {
    rank: 248,
    nome: "(Your Love Keeps Lifting Me) Higher And Higher",
    artist: "Jackie Wilson",
    album: "The Very Best of Jackie Wilson",
    year: "1967",
  },
  {
    rank: 249,
    nome: "The Night They Drove Old Dixie Down",
    artist: "The Band",
    album: "The Band",
    year: "1969",
  },
  {
    rank: 250,
    nome: "Hot Fun In The Summertime",
    artist: "Sly & The Family Stone",
    album: "Greatest Hits",
    year: "1969",
  },
  {
    rank: 251,
    nome: "Rapper's Delight",
    artist: "The Sugarhill Gang",
    album: "Rappers Delight: The Best of Sugarhill Gang",
    year: "1979",
  },
  {
    rank: 252,
    nome: "Chain Of Fools",
    artist: "Aretha Franklin",
    album: "Lady Soul",
    year: "1967",
  },
  {
    rank: 253,
    nome: "Paranoid",
    artist: "Black Sabbath",
    album: "Paranoid",
    year: "1970",
  },
  {
    rank: 254,
    nome: "Money Honey",
    artist: "The Drifters",
    album: "Greatest Hits",
    year: "1953",
  },
  {
    rank: 255,
    nome: "Mack the Knife",
    artist: "Bobby Darin",
    album: "That’s All",
    year: "1959",
  },
  {
    rank: 256,
    nome: "All the Young Dudes",
    artist: "Mott the Hoople",
    album: "All The Young Dudes",
    year: "1972",
  },
  {
    rank: 257,
    nome: "Paranoid Android",
    artist: "Radiohead",
    album: "OK Computer",
    year: "1997",
  },
  {
    rank: 258,
    nome: "Highway To Hell",
    artist: "AC/DC",
    album: "Highway to Hell",
    year: "1979",
  },
  {
    rank: 259,
    nome: "Heart of Glass",
    artist: "Blondie",
    album: "Parallel Lines",
    year: "1978",
  },
  {
    rank: 260,
    nome: "Mississippi",
    artist: "Bob Dylan",
    album: "Love and Theft",
    year: "2001",
  },
  {
    rank: 261,
    nome: "Wild Thing",
    artist: "The Troggs",
    album: "Greatest Hits",
    year: "1966",
  },
  {
    rank: 262,
    nome: "I Can See for Miles",
    artist: "The Who",
    album: "The Who Sell Out",
    year: "1967",
  },
  {
    rank: 263,
    nome: "Oh",
    artist: "The Dells",
    album: "Ultimate Collection",
    year: "1969",
  },
  {
    rank: 264,
    nome: "Hallelujah",
    artist: "Jeff Buckley",
    album: "Grace",
    year: "1994",
  },
  {
    rank: 265,
    nome: "Higher Ground",
    artist: "Stevie Wonder",
    album: "Innervisions",
    year: "1973",
  },
  {
    rank: 266,
    nome: "Ooo Baby Baby",
    artist: "Smokey Robinson and the Miracles",
    album: "Ooo Baby Baby: The Anthology",
    year: "1965",
  },
  {
    rank: 267,
    nome: "He's a Rebel",
    artist: "The Crystals",
    album: "Best of the Crystals",
    year: "1962",
  },
  {
    rank: 268,
    nome: "Sail Away",
    artist: "Randy Newman",
    album: "Sail Away",
    year: "1972",
  },
  {
    rank: 269,
    nome: "Walking In The Rain",
    artist: "The Ronettes",
    album: "The Best of the Ronettes",
    year: "1964",
  },
  {
    rank: 270,
    nome: "Tighten Up",
    artist: "Archie Bell & The Drells",
    album: "Tightening It Up: The Best of Archie Bell and the Drells",
    year: "1968",
  },
  {
    rank: 271,
    nome: "Personality Crisis",
    artist: "New York Dolls",
    album: "New York Dolls",
    year: "1973",
  },
  {
    rank: 272,
    nome: "Sunday Bloody Sunday",
    artist: "U2",
    album: "War",
    year: "1983",
  },
  {
    rank: 273,
    nome: "Jesus Walks",
    artist: "Kanye West",
    album: "The College Dropout",
    year: "2004",
  },
  {
    rank: 274,
    nome: "Roadrunner",
    artist: "The Modern Lovers",
    album: "The Modern Lovers",
    year: "1976",
  },
  {
    rank: 275,
    nome: "He Stopped Loving Her Today",
    artist: "George Jones",
    album: "I Am What I Am",
    year: "1980",
  },
  {
    rank: 276,
    nome: "Sloop John B",
    artist: "The Beach Boys",
    album: "Pet Sounds",
    year: "1966",
  },
  {
    rank: 277,
    nome: "Sweet Little Sixteen",
    artist: "Chuck Berry",
    album: "The Anthology",
    year: "1958",
  },
  {
    rank: 278,
    nome: "Something",
    artist: "The Beatles",
    album: "Abbey Road",
    year: "1969",
  },
  {
    rank: 279,
    nome: "Somebody to Love",
    artist: "Jefferson Airplane",
    album: "Surrealistic Pillow",
    year: "1967",
  },
  {
    rank: 280,
    nome: "Born in the U.S.A.",
    artist: "Bruce Springsteen",
    album: "Born in the U.S.A.",
    year: "1984",
  },
  {
    rank: 281,
    nome: "I'll Take You There",
    artist: "The Staple Singers",
    album: "Bealtitude: Respect Yourself",
    year: "1972",
  },
  {
    rank: 282,
    nome: "Ziggy Stardust",
    artist: "David Bowie",
    album: "The Rise and Fall of Ziggy Stardust and the Spiders Mars",
    year: "1972",
  },
  {
    rank: 283,
    nome: "Pictures of You",
    artist: "The Cure",
    album: "Disintegration",
    year: "1989",
  },
  {
    rank: 284,
    nome: "Chapel Of Love",
    artist: "The Dixie Cups",
    album: "The Best of the Girl Groups, Vol. 1",
    year: "1964",
  },
  {
    rank: 285,
    nome: "Ain't No Sunshine",
    artist: "Bill Withers",
    album: "Lean on Me: The Best of Bill Withers",
    year: "1971",
  },
  {
    rank: 286,
    nome: "Seven Nation Army",
    artist: "The White Stripes",
    album: "Elephant",
    year: "2003",
  },
  {
    rank: 287,
    nome: "You Are the Sunshine of My Life",
    artist: "Stevie Wonder",
    album: "Talking Book",
    year: "1972",
  },
  {
    rank: 288,
    nome: "Help Me",
    artist: "Joni Mitchell",
    album: "Court and Spark",
    year: "1974",
  },
  {
    rank: 289,
    nome: "Call Me",
    artist: "Blondie",
    album: "Best of Blondie",
    year: "1980",
  },
  {
    rank: 290,
    nome: "(What's So Funny 'Bout) Peace, Love And Understanding",
    artist: "Elvis Costello & The Attractions",
    album: "Armed Forces",
    year: "1979",
  },
  {
    rank: 291,
    nome: "Smokestack Lightning",
    artist: "Howlin' Wolf",
    album: "His Best",
    year: "1965",
  },
  {
    rank: 292,
    nome: "Summer Babe (Winter Version)",
    artist: "Pavement",
    album: "Slanted and Enchanted",
    year: "1992",
  },
  {
    rank: 293,
    nome: "Walk This Way",
    artist: "Run-D.M.C.",
    album: "Raising Hell",
    year: "1986",
  },
  {
    rank: 294,
    nome: "Money (That's What I Want)",
    artist: "Barrett Strong",
    album: "Motown: The Classic Years",
    year: "1960",
  },
  {
    rank: 295,
    nome: "Can't Buy Me Love",
    artist: "The Beatles",
    album: "A Hard Day's Night",
    year: "1964",
  },
  {
    rank: 296,
    nome: "Stan (feat. Dido)",
    artist: "Eminem",
    album: "The Marshall Mathers LP",
    year: "2000",
  },
  {
    rank: 297,
    nome: "She's Not There",
    artist: "The Zombies",
    album: "British Invasion: 1963-1967",
    year: "1964",
  },
  {
    rank: 298,
    nome: "Train in Vain",
    artist: "The Clash",
    album: "London Calling",
    year: "1979",
  },
  {
    rank: 299,
    nome: "Tired Of Being Alone",
    artist: "Al Green",
    album: "Greatest Hits",
    year: "1971",
  },
  {
    rank: 300,
    nome: "Black Dog",
    artist: "Led Zeppelin",
    album: "Led Zeppelin IV",
    year: "1971",
  },
  {
    rank: 301,
    nome: "Street Fighting Man",
    artist: "The Rolling Stones",
    album: "Beggars Banquet",
    year: "1968",
  },
  {
    rank: 302,
    nome: "Get Up, Stand Up",
    artist: "Bob Marley & The Wailers",
    album: "Legend",
    year: "1975",
  },
  {
    rank: 303,
    nome: "Heart of Gold",
    artist: "Neil Young",
    album: "Harvest",
    year: "1972",
  },
  {
    rank: 304,
    nome: "Sign 'O' The Times",
    artist: "Prince",
    album: "Sign 'O' The Times",
    year: "1987",
  },
  {
    rank: 305,
    nome: "One Way or Another",
    artist: "Blondie",
    album: "Parallel Lines",
    year: "1978",
  },
  {
    rank: 306,
    nome: "Like a Prayer",
    artist: "Madonna",
    album: "Like a Prayer",
    year: "1989",
  },
  {
    rank: 307,
    nome: "One More Time",
    artist: "Daft Punk",
    album: "Discovery",
    year: "2000",
  },
  {
    rank: 308,
    nome: "Da Ya Think I'm Sexy?",
    artist: "Rod Stewart",
    album: "Blondes Have More Fun",
    year: "1978",
  },
  {
    rank: 309,
    nome: "Blue Eyes Crying In The Rain",
    artist: "Willie Nelson",
    album: "Red Headed Stranger",
    year: "1975",
  },
  {
    rank: 310,
    nome: "Ruby Tuesday",
    artist: "The Rolling Stones",
    album: "Between the Buttons",
    year: "1967",
  },
  {
    rank: 311,
    nome: "With a Little Help My Friends",
    artist: "The Beatles",
    album: "Sgt. Pepper's Lonely Hearts Club Band",
    year: "1967",
  },
  {
    rank: 312,
    nome: "Say It Loud (I'm Black and I'm Proud)",
    artist: "James Brown",
    album: "50th Anniversary Collection",
    year: "1968",
  },
  {
    rank: 313,
    nome: "That's Entertainment",
    artist: "The Jam",
    album: "Sound Affects",
    year: "1980",
  },
  {
    rank: 314,
    nome: "Why Do Fools Fall In Love",
    artist: "Frankie Lymon & The Teenagers",
    album: "The Best of Frankie Lymon and the Teenagers",
    year: "1956",
  },
  {
    rank: 315,
    nome: "Lonely Teardrops",
    artist: "Jackie Wilson",
    album: "The Greatest Hits of Jackie Wilson",
    year: "1958",
  },
  {
    rank: 316,
    nome: "What's Love Got to Do With It",
    artist: "Tina Turner",
    album: "Private Dancer",
    year: "1984",
  },
  {
    rank: 317,
    nome: "Iron Man",
    artist: "Black Sabbath",
    album: "Paranoid",
    year: "1971",
  },
  {
    rank: 318,
    nome: "Wake Up Little Susie",
    artist: "The Everly Brothers",
    album: "The Best of the Everly Brothers",
    year: "1957",
  },
  {
    rank: 319,
    nome: "In Dreams",
    artist: "Roy Orbison",
    album: "For the Lonely: 18 Greatest Hits",
    year: "1963",
  },
  {
    rank: 320,
    nome: "I Put A Spell On You",
    artist: "Screamin' Jay Hawkins",
    album: "Voodoo Jive",
    year: "1956",
  },
  {
    rank: 321,
    nome: "Comfortably Numb",
    artist: "Pink Floyd",
    album: "The Wall",
    year: "1979",
  },
  {
    rank: 322,
    nome: "Don't Let Me Be Misunderstood",
    artist: "The Animals",
    album: "Retrospective",
    year: "1965",
  },
  {
    rank: 323,
    nome: "Alison",
    artist: "Elvis Costello",
    album: "My Aim Is True",
    year: "1977",
  },
  {
    rank: 324,
    nome: "Wish You Were Here",
    artist: "Pink Floyd",
    album: "Wish You Were Here",
    year: "1975",
  },
  {
    rank: 325,
    nome: "Many Rivers to Cross",
    artist: "Jimmy Cliff",
    album: "Wonderful World, Beautiful People",
    year: "1969",
  },
  {
    rank: 326,
    nome: "School's Out",
    artist: "Alice Cooper",
    album: "School's Out",
    year: "1972",
  },
  {
    rank: 327,
    nome: "Take Me Out",
    artist: "Franz Ferdinand",
    album: "Franz Ferdinand",
    year: "2004",
  },
  {
    rank: 328,
    nome: "Heartbreaker",
    artist: "Led Zeppelin",
    album: "Led Zeppelin II",
    year: "1969",
  },
  {
    rank: 329,
    nome: "Cortez the Killer",
    artist: "Neil Young & Crazy Horse",
    album: "Zuma",
    year: "1975",
  },
  {
    rank: 330,
    nome: "Fight the Power",
    artist: "Public Enemy",
    album: "Fear of a Black Planet",
    year: "1989",
  },
  {
    rank: 331,
    nome: "Dancing Barefoot",
    artist: "Patti Smith Group",
    album: "Wave",
    year: "1979",
  },
  {
    rank: 332,
    nome: "Baby Love",
    artist: "The Supremes",
    album: "The Ultimate Collection",
    year: "1964",
  },
  {
    rank: 333,
    nome: "Good Lovin'",
    artist: "The Rascals",
    album: "The Very Best of the Rascals",
    year: "1966",
  },
  {
    rank: 334,
    nome: "Get Up (I Feel Like Being a) Sex Machine",
    artist: "James Brown",
    album: "50th Anniversary Collection",
    year: "1970",
  },
  {
    rank: 335,
    nome: "For Your Precious Love",
    artist: "The Impressions",
    album: "Greatest Hits",
    year: "1958",
  },
  {
    rank: 336,
    nome: "The End",
    artist: "The Doors",
    album: "The Doors",
    year: "1967",
  },
  {
    rank: 337,
    nome: "Wind and Fire",
    artist: "Earth",
    album: "That's The Way of the World",
    year: "1975",
  },
  {
    rank: 338,
    nome: "We Will Rock You",
    artist: "Queen",
    album: "News of the World",
    year: "1977",
  },
  {
    rank: 339,
    nome: "I Can't Make You Love Me",
    artist: "Bonnie Raitt",
    album: "Luck of the Draw",
    year: "1991",
  },
  {
    rank: 340,
    nome: "Subterranean Homesick Blues",
    artist: "Bob Dylan",
    album: "Bringing It All Back Home",
    year: "1965",
  },
  {
    rank: 341,
    nome: "Spirit in the Sky",
    artist: "Norman Greenbaum",
    album: "Spirit in the Sky",
    year: "1970",
  },
  {
    rank: 342,
    nome: "Sweet Jane",
    artist: "The Velvet Underground",
    album: "Loaded (Fully Loaded Edition)",
    year: "1970",
  },
  {
    rank: 343,
    nome: "Wild Horses",
    artist: "The Rolling Stones",
    album: "Sticky Fingers",
    year: "1971",
  },
  {
    rank: 344,
    nome: "Beat It",
    artist: "Michael Jackson",
    album: "Thriller",
    year: "1982",
  },
  {
    rank: 345,
    nome: "Beautiful Day",
    artist: "U2",
    album: "All That You Can't Leave Behind",
    year: "2000",
  },
  {
    rank: 346,
    nome: "Walk This Way",
    artist: "Aerosmith",
    album: "Toys in the Attic",
    year: "1975",
  },
  {
    rank: 347,
    nome: "Maybe I'm Amazed",
    artist: "Paul McCartney",
    album: "McCartney",
    year: "1970",
  },
  {
    rank: 348,
    nome: "You Keep Me Hangin' On",
    artist: "The Supremes",
    album: "The Ultimate Collection",
    year: "1966",
  },
  {
    rank: 349,
    nome: "Baba O'Riley",
    artist: "The Who",
    album: "Who's Next",
    year: "1971",
  },
  {
    rank: 350,
    nome: "The Harder They Come",
    artist: "Jimmy Cliff",
    album: "The Harder They Come",
    year: "1975",
  },
  {
    rank: 351,
    nome: "Runaround Sue",
    artist: "Dion",
    album: "Runaround Sue",
    year: "1961",
  },
  {
    rank: 352,
    nome: "Jim Dandy",
    artist: "Lavern Baker",
    album: "Soul on Fire: The Best of LaVern Baker",
    year: "1956",
  },
  {
    rank: 353,
    nome: "Piece of My Heart",
    artist: "Big Brother & The Holding Company",
    album: "Cheap Thrills",
    year: "1968",
  },
  {
    rank: 354,
    nome: "La Bamba",
    artist: "Ritchie Valens",
    album: "The Ritchie Valens Story",
    year: "1958",
  },
  {
    rank: 355,
    nome: "California Love (remix) (feat. Dr. Dre & Roger Troutman)",
    artist: "2Pac",
    album: "Greatest Hits",
    year: "1996",
  },
  {
    rank: 356,
    nome: "Candle in the Wind",
    artist: "Elton John",
    album: "Goodbye Yellow Brick Road",
    year: "1973",
  },
  {
    rank: 357,
    nome: "That Lady (Parts 1 & 2)",
    artist: "The Isley Brothers",
    album: "The Essential Isley Brothers",
    year: "1973",
  },
  {
    rank: 358,
    nome: "Spanish Harlem",
    artist: "Ben E. King",
    album: "The Very Best of Ben E. King",
    year: "1960",
  },
  {
    rank: 359,
    nome: "The Loco-Motion",
    artist: "Little Eva",
    album: "The Loco-Motion",
    year: "1962",
  },
  {
    rank: 360,
    nome: "The Great Pretender",
    artist: "The Platters",
    album: "The Magic Touch: An Anthology",
    year: "1955",
  },
  {
    rank: 361,
    nome: "All Shook Up",
    artist: "Elvis Presley",
    album: "Elvis 30 #1 Hits",
    year: "1957",
  },
  {
    rank: 362,
    nome: "Tears in Heaven",
    artist: "Eric Clapton",
    album: '"Rush" Soundtrack',
    year: "1992",
  },
  {
    rank: 363,
    nome: "Watching The Detectives",
    artist: "Elvis Costello",
    album: "My Aim Is True",
    year: "1977",
  },
  {
    rank: 364,
    nome: "Bad Moon Rising",
    artist: "Creedence Clearwater Revival",
    album: "Green River",
    year: "1969",
  },
  {
    rank: 365,
    nome: "Sweet Dreams (Are Made of This)",
    artist: "Eurythmics",
    album: "Sweet Dreams",
    year: "1983",
  },
  {
    rank: 366,
    nome: "Little Wing",
    artist: "The Jimi Hendrix Experience",
    album: "Axis: Bold As Love",
    year: "1968",
  },
  {
    rank: 367,
    nome: "Nowhere To Run",
    artist: "Martha and the Vandellas",
    album: "The Ultimate Collection",
    year: "1965",
  },
  {
    rank: 368,
    nome: "Got My Mojo Working",
    artist: "Muddy Waters",
    album: "The Anthology",
    year: "1957",
  },
  {
    rank: 369,
    nome: "Killing Me Softly With His Song",
    artist: "Roberta Flack",
    album: "Killing Me Softly",
    year: "1973",
  },
  {
    rank: 370,
    nome: "All You Need Is Love",
    artist: "The Beatles",
    album: "Magical Mystery Tour",
    year: "1967",
  },
  {
    rank: 371,
    nome: "Complete Control",
    artist: "The Clash",
    album: "The Clash",
    year: "1979",
  },
  {
    rank: 372,
    nome: "The Letter",
    artist: "The Box Tops",
    album: "The Letter",
    year: "1967",
  },
  {
    rank: 373,
    nome: "Highway 61 Revisited",
    artist: "Bob Dylan",
    album: "Highway 61 Revisited",
    year: "1965",
  },
  {
    rank: 374,
    nome: "Unchained Melody",
    artist: "The Righteous Brothers",
    album: "Anthology 1962-1974",
    year: "1965",
  },
  {
    rank: 375,
    nome: "How Deep Is Your Love",
    artist: "Bee Gees",
    album: "Saturday Night Fever",
    year: "1977",
  },
  {
    rank: 376,
    nome: "White Room",
    artist: "Cream",
    album: "Wheels Of Fire",
    year: "1968",
  },
  {
    rank: 377,
    nome: "Personal Jesus",
    artist: "Depeche Mode",
    album: "Violator",
    year: "1989",
  },
  {
    rank: 378,
    nome: "I'm A Man",
    artist: "Bo Diddley",
    album: "His Best: The Chess 50th Anniversary Collection",
    year: "1955",
  },
  {
    rank: 379,
    nome: "The Wind Cries Mary",
    artist: "The Jimi Hendrix Experience",
    album: "Are You Experienced?",
    year: "1967",
  },
  {
    rank: 380,
    nome: "I Can't Explain",
    artist: "The Who",
    album: "The Ultimate Collection",
    year: "1965",
  },
  {
    rank: 381,
    nome: "Marquee Moon",
    artist: "Television",
    album: "Marquee Moon",
    year: "1977",
  },
  {
    rank: 382,
    nome: "Wonderful World",
    artist: "Sam Cooke",
    album: "Portrait of a Legend 1951-1964",
    year: "1960",
  },
  {
    rank: 383,
    nome: "Brown Eyed Handsome Man",
    artist: "Chuck Berry",
    album: "The Anthology",
    year: "1956",
  },
  {
    rank: 384,
    nome: "Another Brick In The Wall (Part II)",
    artist: "Pink Floyd",
    album: "The Wall",
    year: "1979",
  },
  {
    rank: 385,
    nome: "Fake Plastic Trees",
    artist: "Radiohead",
    album: "The Bends",
    year: "1995",
  },
  {
    rank: 386,
    nome: "Maps",
    artist: "Yeah Yeah Yeahs",
    album: "Fever to Tell",
    year: "2004",
  },
  {
    rank: 387,
    nome: "Hit the Road Jack",
    artist: "Ray Charles",
    album: "Ultimate Hits Collection",
    year: "1961",
  },
  {
    rank: 388,
    nome: "Pride (in the Name of Love)",
    artist: "U2",
    album: "The Unforgettable Fire",
    year: "1984",
  },
  {
    rank: 389,
    nome: "Radio Free Europe",
    artist: "R.E.M.",
    album: "Murmur",
    year: "1983",
  },
  {
    rank: 390,
    nome: "Goodbye Yellow Brick Road",
    artist: "Elton John",
    album: "Goodbye Yellow Brick Road",
    year: "1973",
  },
  {
    rank: 391,
    nome: "Tell It Like It Is",
    artist: "Aaron Neville",
    album: "Tell It Like It Is: Golden Classics",
    year: "1965",
  },
  {
    rank: 392,
    nome: "Bitter Sweet Symphony",
    artist: "The Verve",
    album: "Urban Hymns",
    year: "1997",
  },
  {
    rank: 393,
    nome: "Whipping Post",
    artist: "The Allman Brothers Band",
    album: "At Fillmore East",
    year: "1971",
  },
  {
    rank: 394,
    nome: "Ticket to Ride",
    artist: "The Beatles",
    album: "Help!",
    year: "1965",
  },
  {
    rank: 395,
    nome: "Stills, Nash & Young",
    artist: "Crosby",
    album: "Decade",
    year: "1970",
  },
  {
    rank: 396,
    nome: "I Know You Got Soul",
    artist: "Eric B. & Rakim",
    album: "Paid In Full",
    year: "1987",
  },
  {
    rank: 397,
    nome: "Tiny Dancer",
    artist: "Elton John",
    album: "Madman Across the Water",
    year: "1972",
  },
  {
    rank: 398,
    nome: "Roxanne",
    artist: "The Police",
    album: "Outlandos d'Amour",
    year: "1978",
  },
  {
    rank: 399,
    nome: "Just My Imagination (Running Away With Me)",
    artist: "The Temptations",
    album: "Anthology",
    year: "1971",
  },
  {
    rank: 400,
    nome: "Baby I Need Your Loving",
    artist: "The Four Tops",
    album: "The Ultimate Collection",
    year: "1965",
  },
  {
    rank: 401,
    nome: "Summer in the City",
    artist: "The Lovin' Spoonful",
    album: "The Lovin' Spoonful Greatest Hits",
    year: "1966",
  },
  {
    rank: 402,
    nome: "O-o-h Child",
    artist: "The Five Stairsteps",
    album: "Soul Hits of the '70s: Didn't It Blow Your Mind! Vol. 2",
    year: "1970",
  },
  {
    rank: 403,
    nome: "Can't Help Falling in Love",
    artist: "Elvis Presley",
    album: "Elvis 30 #1 Hits",
    year: "1961",
  },
  {
    rank: 404,
    nome: "Remember (Walkin' In The Sand)",
    artist: "The Shangri-Las",
    album: "The Best of the Shangri-Las",
    year: "1964",
  },
  {
    rank: 405,
    nome: "(Don't Fear) The Reaper",
    artist: "Blue Öyster Cult",
    album: "Agents of Fortune",
    year: "1976",
  },
  {
    rank: 406,
    nome: "Thirteen",
    artist: "Big Star",
    album: "#1 Record/Radio City",
    year: "1972",
  },
  {
    rank: 407,
    nome: "Sweet Home Alabama",
    artist: "Lynyrd Skynyrd",
    album: "Second Helping",
    year: "1974",
  },
  {
    rank: 408,
    nome: "Enter Sandman",
    artist: "Metallica",
    album: "Metallica",
    year: "1991",
  },
  {
    rank: 409,
    nome: "Tonight's the Night",
    artist: "The Shirelles",
    album: "25 All-Time Greatest Hits",
    year: "1960",
  },
  {
    rank: 410,
    nome: "Thank You (Falettinme Be Mice Elf Agin)",
    artist: "Sly & The Family Stone",
    album: "Greatest Hits",
    year: "1970",
  },
  {
    rank: 411,
    nome: "C'mon Everybody",
    artist: "Eddie Cochran",
    album: "Anthology",
    year: "1958",
  },
  {
    rank: 412,
    nome: "Umbrella (feat. Jay-Z)",
    artist: "Rihanna",
    album: "Good Girl Gone Bad",
    year: "2007",
  },
  {
    rank: 413,
    nome: "Visions of Johanna",
    artist: "Bob Dylan",
    album: "Blonde on Blonde",
    year: "1966",
  },
  {
    rank: 414,
    nome: "We've Only Just Begun",
    artist: "Carpenters",
    album: "Singles 1969-1981",
    year: "1971",
  },
  {
    rank: 415,
    nome: "In Bloom",
    artist: "Nirvana",
    album: "Nevermind",
    year: "1991",
  },
  {
    rank: 416,
    nome: "Sweet Emotion",
    artist: "Aerosmith",
    album: "Toys in the Attic",
    year: "1975",
  },
  {
    rank: 417,
    nome: "Monkey Gone to Heaven",
    artist: "Pixies",
    album: "Doolittle",
    year: "1989",
  },
  {
    rank: 418,
    nome: "I Feel Love",
    artist: "Donna Summer",
    album: "The Donna Summer Anthology",
    year: "1977",
  },
  {
    rank: 419,
    nome: "Ode to Billie Joe",
    artist: "Bobbie Gentry",
    album: "Greatest Hits",
    year: "1967",
  },
  {
    rank: 420,
    nome: "The Girl Can't Help It",
    artist: "Little Richard",
    album: "The Georgia Peach",
    year: "1957",
  },
  {
    rank: 421,
    nome: "Young Blood",
    artist: "The Coasters",
    album: "The Very Best of the Coasters",
    year: "1957",
  },
  {
    rank: 422,
    nome: "I Can't Help Myself",
    artist: "The Four Tops",
    album: "The Ultimate Collection",
    year: "1965",
  },
  {
    rank: 423,
    nome: "The Boys Of Summer",
    artist: "Don Henley",
    album: "Building the Perfect Beast",
    year: "1984",
  },
  {
    rank: 424,
    nome: "Juicy",
    artist: "The Notorious B.I.G",
    album: "Ready to Die",
    year: "1994",
  },
  {
    rank: 425,
    nome: "Fuck tha Police",
    artist: "N.W.A",
    album: "Straight Outta Compton",
    year: "1988",
  },
  {
    rank: 426,
    nome: "Stills & Nash, Suite: Judy Blue Eyes",
    artist: "Crosby",
    album: "Crosby, Stills and Nash",
    year: "1969",
  },
  {
    rank: 427,
    nome: "Nuthin' but a 'G' Thang",
    artist: "Dr. Dre",
    album: "The Chronic",
    year: "1993",
  },
  {
    rank: 428,
    nome: "It's Your Thing",
    artist: "The Isley Brothers",
    album: "The Ultimate Isley Brothers",
    year: "1969",
  },
  {
    rank: 429,
    nome: "Piano Man",
    artist: "Billy Joel",
    album: "Piano Man",
    year: "1973",
  },
  {
    rank: 430,
    nome: "Blue Suede Shoes",
    artist: "Elvis Presley",
    album: "2nd to None",
    year: "1956",
  },
  {
    rank: 431,
    nome: "William",
    artist: "The Smiths",
    album: "Louder Than Bombs",
    year: "1984",
  },
  {
    rank: 432,
    nome: "American Idiot",
    artist: "Green day",
    album: "American Idiot",
    year: "2004",
  },
  {
    rank: 433,
    nome: "Tumbling Dice",
    artist: "The Rolling Stones",
    album: "Exile on Main Street",
    year: "1972",
  },
  {
    rank: 434,
    nome: "Smoke on the Water",
    artist: "Deep Purple",
    album: "Machine Head",
    year: "1972",
  },
  {
    rank: 435,
    nome: "New Year's Day",
    artist: "U2",
    album: "War",
    year: "1983",
  },
  {
    rank: 436,
    nome: "Everybody Needs Somebody To Love",
    artist: "Solomon Burke",
    album: "The Very Best of Solomon Burke",
    year: "1964",
  },
  {
    rank: 437,
    nome: "(White Man) In Hammersmith Palais",
    artist: "The Clash",
    album: "The Clash",
    year: "1978",
  },
  {
    rank: 438,
    nome: "Ain't That a Shame",
    artist: "Fats Domino",
    album: "The Fats Domino Jukebox: 20 Greatest Hits",
    year: "1955",
  },
  {
    rank: 439,
    nome: "Midnight Train To Georgia",
    artist: "Gladys Knight & The Pips",
    album: "Essential Collection",
    year: "1977",
  },
  {
    rank: 440,
    nome: "Ramble On",
    artist: "Led Zeppelin",
    album: "Led Zeppelin II",
    year: "1969",
  },
  {
    rank: 441,
    nome: "Mustang Sally",
    artist: "Wilson Pickett",
    album: "The Very Best of Wilson Pickett",
    year: "1966",
  },
  {
    rank: 442,
    nome: "Alone Again Or",
    artist: "Love",
    album: "Forever Changes",
    year: "1967",
  },
  {
    rank: 443,
    nome: "Beast of Burden",
    artist: "The Rolling Stones",
    album: "Some Girls",
    year: "1981",
  },
  {
    rank: 444,
    nome: "Love Me Tender",
    artist: "Elvis Presley",
    album: "Elvis: 30 #1 Hits",
    year: "1956",
  },
  {
    rank: 445,
    nome: "I Wanna Be Your Dog",
    artist: "The Stooges",
    album: "The Stooges",
    year: "1969",
  },
  {
    rank: 446,
    nome: "Push It",
    artist: "Salt-N-Pepa",
    album: "Hot, Cool and Vicious",
    year: "1987",
  },
  {
    rank: 447,
    nome: "Pink Houses",
    artist: "John Mellencamp",
    album: "Uh-Huh",
    year: "1984",
  },
  {
    rank: 448,
    nome: "In Da Club",
    artist: "50 Cent",
    album: "Get Rich or Die Tryin'",
    year: "2003",
  },
  {
    rank: 449,
    nome: "Come Go With Me",
    artist: "The Del-Vikings",
    album: "Golden Classics",
    year: "1957",
  },
  {
    rank: 450,
    nome: "I Shot The Sheriff",
    artist: "Bob Marley & The Wailers",
    album: "Burnin'",
    year: "1973",
  },
  {
    rank: 451,
    nome: "I Got You Babe",
    artist: "Sonny & Cher",
    album: "The Beat Goes On: The Best of Sonny and Cher",
    year: "1965",
  },
  {
    rank: 452,
    nome: "Come as You Are",
    artist: "Nirvana",
    album: "Nevermind",
    year: "1992",
  },
  {
    rank: 453,
    nome: "Pressure Drop",
    artist: "Toot and the Maytals",
    album: "The Harder They Come",
    year: "1968",
  },
  {
    rank: 454,
    nome: "Leader of the Pack",
    artist: "The Shangri-Las",
    album: "Myrmidons of Melodrama: Definitive Collection",
    year: "1964",
  },
  {
    rank: 455,
    nome: "Heroin",
    artist: "The Velvet Underground",
    album: "The Velvet Underground & Nico",
    year: "1967",
  },
  {
    rank: 456,
    nome: "Penny Lane",
    artist: "The Beatles",
    album: "Magical Mystery Tour",
    year: "1967",
  },
  {
    rank: 457,
    nome: "The Twist",
    artist: "Chubby Checker",
    album: "Greatest Hits",
    year: "1960",
  },
  {
    rank: 458,
    nome: "Cupid",
    artist: "Sam Cooke",
    album: "Greatest Hits",
    year: "1961",
  },
  {
    rank: 459,
    nome: "Paradise City",
    artist: "Guns N' Roses",
    album: "Appetite for Destruction",
    year: "1987",
  },
  {
    rank: 460,
    nome: "My Sweet Lord",
    artist: "George Harrison",
    album: "All Things Must Pass",
    year: "1970",
  },
  {
    rank: 461,
    nome: "Sheena Is a Punk Rocker",
    artist: "Ramones",
    album: "Rocket to Russia",
    year: "1977",
  },
  {
    rank: 462,
    nome: "All Apologies",
    artist: "Nirvana",
    album: "In Utero",
    year: "1993",
  },
  {
    rank: 463,
    nome: "Soul Man",
    artist: "Sam & Dave",
    album: "Soul Men",
    year: "1965",
  },
  {
    rank: 464,
    nome: "Kiss",
    artist: "Prince and The Revolution",
    album: "Parade",
    year: "1986",
  },
  {
    rank: 465,
    nome: "Rollin' Stone",
    artist: "Muddy Waters",
    album: "The Anthology: 1947-1972",
    year: "1948",
  },
  {
    rank: 466,
    nome: "Get Ur Freak On",
    artist: "Missy Elliott",
    album: "Miss E … So Addictive",
    year: "2001",
  },
  {
    rank: 467,
    nome: "Big Pimpin' (feat. UGK)",
    artist: "Jay-Z",
    album: "Vol. 3: Life and Times of S. Carter",
    year: "2000",
  },
  {
    rank: 468,
    nome: "Respect Yourself",
    artist: "The Staple Singers",
    album: "Bealtitude: Respect Yourself",
    year: "1972",
  },
  {
    rank: 469,
    nome: "Rain",
    artist: "The Beatles",
    album: "Past Masters",
    year: "1966",
  },
  {
    rank: 470,
    nome: "Standing In The Shadows Of Love",
    artist: "The Four Tops",
    album: "The Ultimate Collection",
    year: "1966",
  },
  {
    rank: 471,
    nome: "Surrender",
    artist: "Cheap Trick",
    album: "Heaven Tonight",
    year: "1978",
  },
  {
    rank: 472,
    nome: "Runaway",
    artist: "Del Shannon",
    album: "Greatest Hits",
    year: "1961",
  },
  {
    rank: 473,
    nome: "Welcome to the Jungle",
    artist: "Guns N' Roses",
    album: "Appetite for Destruction",
    year: "1987",
  },
  {
    rank: 474,
    nome: "Into The Mystic",
    artist: "Van Morrison",
    album: "Moondance",
    year: "1970",
  },
  {
    rank: 475,
    nome: "Where Did Our Love Go",
    artist: "The Supremes",
    album: "The Ultimate Collection",
    year: "1964",
  },
  {
    rank: 476,
    nome: "Do Right Woman, Do Right Man",
    artist: "Aretha Franklin",
    album: "I Never Loved a Man the Way I Love You",
    year: "1967",
  },
  {
    rank: 477,
    nome: "How Soon Is Now?",
    artist: "The Smiths",
    album: "Meat Is Murder",
    year: "1984",
  },
  {
    rank: 478,
    nome: "Last Nite",
    artist: "The Strokes",
    album: "Is This It",
    year: "2001",
  },
  {
    rank: 479,
    nome: "I Want To Know What Love Is",
    artist: "Foreigner",
    album: "Agent Provocateur",
    year: "1984",
  },
  {
    rank: 480,
    nome: "Sabotage",
    artist: "Beastie Boys",
    album: "Ill Communication",
    year: "1994",
  },
  {
    rank: 481,
    nome: "Super Freak",
    artist: "Rick James",
    album: "Street Songs",
    year: "1981",
  },
  {
    rank: 482,
    nome: "Since U Been Gone",
    artist: "Kelly Clarkson",
    album: "Breakaway",
    year: "2004",
  },
  {
    rank: 483,
    nome: "White Rabbit",
    artist: "Jefferson Airplane",
    album: "Surrealistic Pillow",
    year: "1967",
  },
  {
    rank: 484,
    nome: "Cry Me a River",
    artist: "Justin Timberlake",
    album: "Justified",
    year: "2002",
  },
  {
    rank: 485,
    nome: "Lady Marmalade",
    artist: "Labelle",
    album: "Nightbirds",
    year: "1974",
  },
  {
    rank: 486,
    nome: "Young Americans",
    artist: "David Bowie",
    album: "Young Americans",
    year: "1975",
  },
  {
    rank: 487,
    nome: "I'm Eighteen",
    artist: "Alice Cooper",
    album: "Love It to Death",
    year: "1971",
  },
  {
    rank: 488,
    nome: "Just Like Heaven",
    artist: "The Cure",
    album: "Kiss Me, Kiss Me, Kiss Me",
    year: "1987",
  },
  {
    rank: 489,
    nome: "Under the Boardwalk",
    artist: "The Drifters",
    album: "The Very Best of the Drifters",
    year: "1964",
  },
  {
    rank: 490,
    nome: "Clocks",
    artist: "Coldplay",
    album: "A Rush of Blood to the Head",
    year: "2002",
  },
  {
    rank: 491,
    nome: "I Love Rock 'N Roll",
    artist: "Joan Jett and The Blackhearts",
    album: "I Love Rock 'N Roll",
    year: "1981",
  },
  {
    rank: 492,
    nome: "I Will Survive",
    artist: "Gloria Gaynor",
    album: "I Will Survive: The Anthology",
    year: "1978",
  },
  {
    rank: 493,
    nome: "Time to Pretend",
    artist: "MGMT",
    album: "Oracular Spectacular",
    year: "2008",
  },
  {
    rank: 494,
    nome: "Ignition (Remix)",
    artist: "R. Kelly",
    album: "Chocolate Factory",
    year: "2003",
  },
  {
    rank: 495,
    nome: "Brown Sugar",
    artist: "The Rolling Stones",
    album: "Sticky Fingers",
    year: "1971",
  },
  {
    rank: 496,
    nome: "Running On Empty",
    artist: "Jackson Browne",
    album: "Running on Empty",
    year: "1977",
  },
  {
    rank: 497,
    nome: "The Rising",
    artist: "Bruce Springsteen",
    album: "The Rising",
    year: "2002",
  },
  {
    rank: 498,
    nome: "Miss You",
    artist: "The Rolling Stones",
    album: "Some Girls",
    year: "1978",
  },
  {
    rank: 499,
    nome: "Buddy Holly",
    artist: "Weezer",
    album: "Weezer",
    year: "1994",
  },
  {
    rank: 500,
    nome: "Shop Around",
    artist: "Smokey Robinson and the Miracles",
    album: "The Ultimate Collection",
    year: "1960",
  },
];

export { musicas }